config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(params_list)
    if @list.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def params_list
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<h3>Add a movie</h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-5">
  <h1 class = "text-center display-1 m-5 shadow-lg fw-bold">🎥 List of Movies 🎥</h1>
  <div class="row justify-content-center">
    <ul class="list-group shadow-sm">
      <% @lists.each do |list| %>
        <li class="list-group-item list-group-item-action d-flex align-items-center justify-content-between"><%= link_to list.name, list_path(list), class:"text-dark fw-semibold" %>🍿</li>
      <% end %>
    </ul>
    <div class="text-center m-3">
  </div>
    <%= link_to new_list_path, data: { turbo: true, turbo_frame: "modal" }, class: "btn btn-lg btn-success shadow-sm" do %>
      ➕
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a List</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name, placeholder: 'Add a name' %>
  <%= f.submit "Create" %>
<% end %>

app/views/lists/show.html.erb
<div class="container m-4">
  <div class="d-flex justify-content-between align-items-center">
    <h2><%= @list.name %></h2>
    <%= link_to "delete this list", @list, method: :delete, data: { confirm: 'Are you sure to delete this list ?' } %>
  </div>
  <button type="button" class="btn btn-primary mt-3" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
    Add a Movie
  </button>
  <div class="row mt-4">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="card shadow-sm">
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %> <span class="badge bg-success"><%= movie.rating %></span></h5>
            <p class="card-text"><%= movie.overview %></p>
          </div>
        </div>
    <% end %>
  </div>
</div>